import publicIds from '../../constants/cloudinary_static_public_ids';

const LatestMusicData=[
   {
      id: 11,
      image: publicIds.happyImg,
      title: 'Egire Mabbulalona Telugu Video Song || Happy Movie || Allu Arjun, Genelia',
      subTitle: 'Trend Music',
      views: '9.5M views',
      daysMonths:'2 days',
      video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
   },
   {
    id: 12,
    image: publicIds.yedaPoyinadoImg,
    title: 'Yeda Poyinado - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S',
    subTitle: 'Trend Music',
    views: '1.5k views',
    daysMonths:'9 Months',
    video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
 },
 {
    id: 13,
    image: publicIds.reddamaThali,
    title: 'Reddamma Thalli Video Song Promo | Aravindha Sametha Veera Raghava',
    subTitle: 'Trend Music',
    views: '9.5M views',
    daysMonths:'2 days',
    video: 'Reddamma Thalli - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S | Trivikram',
 },
 {
    id: 14,
    image: publicIds.yedaPoyinadoImg,
    title: 'Yeda Poyinado - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S',
    subTitle: 'Trend Music',
    views: '1.5k views',
    daysMonths:'9 Months',
    video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
 },
 {
    id: 15,
    image: publicIds.happyImg,
    title: 'Egire Mabbulalona Telugu Video Song || Happy Movie || Allu Arjun, Genelia',
    subTitle: 'Trend Music',
    views: '9.5M views',
    daysMonths:'2 days',
    video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
 },
 {
    id: 16,
    image: publicIds.reddamaThali,
    title: 'Reddamma Thalli Video Song Promo | Aravindha Sametha Veera Raghava',
    subTitle: 'Trend Music',
    views: '1.5k views',
    daysMonths:'9 Months',
    video: 'Reddamma Thalli - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S | Trivikram',
 },
 {
    id: 17,
    image: publicIds.happyImg,
    title: 'Egire Mabbulalona Telugu Video Song || Happy Movie || Allu Arjun, Genelia',
    subTitle: 'Trend Music',
    views: '9.5M views',
    daysMonths:'2 days',
    video: 'video',
 },
 {
   id: 18,
   image: publicIds.happyImg,
   title: 'Egire Mabbulalona Telugu Video Song || Happy Movie || Allu Arjun, Genelia',
   subTitle: 'Trend Music',
   views: '1.5k views',
   daysMonths:'9 Months',
   video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
},
{
 id: 19,
 image: publicIds.yedaPoyinadoImg,
 title: 'Yeda Poyinado - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S',
 subTitle: 'Trend Music',
 views: '9.5M views',
    daysMonths:'2 days',
 video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
},
{
 id: 20,
 image: publicIds.reddamaThali,
 title: 'Reddamma Thalli Video Song Promo | Aravindha Sametha Veera Raghava',
 subTitle: 'Trend Music',
 views: '1.5k views',
 daysMonths:'9 Months',
 video: 'Reddamma Thalli - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S | Trivikram',
},
{
 id: 21,
 image: publicIds.yedaPoyinadoImg,
 title: 'Yeda Poyinado - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S',
 subTitle: 'Trend Music',
 views: '9.5M views',
  daysMonths:'2 days',
 video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
},
{
 id: 22,
 image: publicIds.happyImg,
 title: 'Egire Mabbulalona Telugu Video Song || Happy Movie || Allu Arjun, Genelia',
 subTitle: 'Trend Music',
 views: '1.5k views',
 daysMonths:'9 Months',
 video: '//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
},
{
 id: 23,
 image: publicIds.reddamaThali,
 title: 'Reddamma Thalli Video Song Promo | Aravindha Sametha Veera Raghava',
 subTitle: 'Trend Music',
 views: '9.5M views',
    daysMonths:'2 days',
 video: 'Reddamma Thalli - Full Video | Aravindha Sametha | Jr. NTR, Pooja Hegde | Thaman S | Trivikram',
},
{
 id: 24,
 image: publicIds.happyImg,
 title: 'Egire Mabbulalona Telugu Video Song || Happy Movie || Allu Arjun, Genelia',
 subTitle: 'Trend Music',
 views: '1.5k views',
 daysMonths:'9 Months',
 video: 'video',
},
 ]
 
 export default LatestMusicData;